# Generated by Django 5.2.1 on 2026-02-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('spike', 'Power Spike'), ('overload', 'Overload'), ('low_pf', 'Low Power Factor'), ('fault', 'Electrical Fault'), ('unusual', 'Unusual Pattern')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('school', 'School'), ('commercial', 'Commercial'), ('government', 'Government')], max_length=20)),
                ('address', models.TextField()),
                ('total_floors', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('power_usage', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('frequency', models.FloatField(default=60.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed')], default='sent', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.FloatField(blank=True, null=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.anomaly')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='energy_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.energyreading'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('main_panel', 'Main Panel'), ('appliance', 'Appliance'), ('hvac', 'HVAC'), ('lighting', 'Lighting')], max_length=20)),
                ('location_in_building', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitoring.building')),
            ],
        ),
        migrations.AddField(
            model_name='energyreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensor'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.sensor'),
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['sensor', 'timestamp'], name='monitoring__sensor__d893ff_idx'),
        ),
    ]
